### ISSUE TITLE
First two arguments of UI.SetValue & UI.GetValue aren't mandatory

### ISSUE THREAD

**Issue by undef093** [MasedMSD/MSDSquad#3]
![image](https://user-images.githubusercontent.com/108448788/209127761-9877790d-2f4f-4bca-a019-c0387458f322.png)
![image](https://user-images.githubusercontent.com/108448788/209128240-5d7b9fdb-a186-4d55-83e5-95140dea81d4.png)
![image](https://user-images.githubusercontent.com/108448788/209128777-28899d58-ed3c-44d1-9442-ee6920c01955.png)

**Comment by MasedMSD** [comment]
В первом случае я рассчитывал на то, что люди будут прописывать полный путь.
А Anti-Aim просто криворукий делал без сабтабов. Потом укажу как необязательные

**Comment by undef093** [comment]
Возможное решение:

`function SetValue <N extends string> (Area: string, name: N, value: boolean | 1 | 0): void;`
`function GetValue <N extends string> (Area: string, name: N): boolean | 1 | 0;`

**Comment by MasedMSD** [comment]
я думаю просто Tab и Subtab сделать optional

**Comment by undef093** [comment]
> я думаю просто Tab и Subtab сделать optional

Компилятор так не считает
![image](https://user-images.githubusercontent.com/108448788/209130096-b24f8b99-dd92-4e31-8c2d-aa334cf4371a.png)

**Comment by undef093** [comment]
> Хотя наверное проще их убрать будет
Зачем? Можно создать копии фукнций

`function GetValue <T extends keyof Subtabs, N extends string> (Tab: T, Area: string, name: N): boolean | 1 | 0`
`function GetValue <N extends string> (Area: string, name: N): boolean | 1 | 0;`
`function SetValue <T extends keyof Subtabs, N extends string> (Tab: T, Area: string, name: N, value: boolean | 1 | 0): void;`
`function SetValue <N extends string> (Area: string, name: N, value: boolean | 1 | 0): void;`
